-- Note: Test users (admin@sizehub.local and demo@sizehub.local) need to be created
-- manually after running migrations using: scripts/create-test-users.sh
-- This is because Supabase GoTrue uses its own password hashing that cannot be
-- replicated in SQL migrations.
